import {
  JayaramMittaiCategory,
  JayaramMittaiProduct,
  JayaramMittaiDeliveryZone,
  JayaramMittaiDeliveryRule,
  JayaramMittaiOperationalHours,
} from './types';

export const SEED_CATEGORIES: JayaramMittaiCategory[] = [
  {
    id: 'cat-sweets',
    name: 'Authentic Sweets',
    sort_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-beverages',
    name: 'Fresh Juices & Milkshakes',
    sort_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-tikkas',
    name: 'Tikkas & Starters',
    sort_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-rice',
    name: 'Fried Rice & Bowls',
    sort_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-breads',
    name: 'Naan & Stuffed Parathas',
    sort_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-combos',
    name: 'Festive Gift Boxes',
    sort_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_PRODUCTS: JayaramMittaiProduct[] = [
  // ── Sweets ──
  {
    id: 'prod-rasamalai',
    category_id: 'cat-sweets',
    name: 'Royal Rasamalai',
    description: 'Soft cottage cheese patties soaked in thickened saffron and cardamom infused milk, topped with pistachio slivers.',
    price: 120,
    unit: '2 pcs',
    image_url: '/images/food/Rasamalai_plated_on_white_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-rasamalai',
      product_id: 'prod-rasamalai',
      is_available: true,
      available_start_time: '09:00:00',
      available_end_time: '21:00:00',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-basundi',
    category_id: 'cat-sweets',
    name: 'Rich Badam Basundi',
    description: 'Slow-simmered sweetened milk reduced to perfection with roasted almonds, saffron, and nutmeg.',
    price: 140,
    unit: '250g',
    image_url: '/images/food/Basundi_plated_on_white_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-basundi',
      product_id: 'prod-basundi',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-black-forest',
    category_id: 'cat-sweets',
    name: 'Special Black Forest Slice',
    description: 'Delicate chocolate sponge cake layered with fresh whipped cream, dark cherries, and chocolate shavings.',
    price: 110,
    unit: '1 slice',
    image_url: '/images/food/Black_Forest_Cake_plated_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-black-forest',
      product_id: 'prod-black-forest',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },

  // ── Beverages ──
  {
    id: 'prod-badam-milk',
    category_id: 'cat-beverages',
    name: 'Pure Kesari Badam Milk',
    description: 'Chilled rich milk blended with almond paste, infused with Kashmiri saffron and cardamom.',
    price: 90,
    unit: '300ml',
    image_url: '/images/food/Badam_milk_in_glass_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-badam-milk',
      product_id: 'prod-badam-milk',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-rose-milk',
    category_id: 'cat-beverages',
    name: 'Signature Rose Milk',
    description: 'Traditional refreshing milk infused with pure Damascus rose essence and sabja seeds.',
    price: 75,
    unit: '300ml',
    image_url: '/images/food/Rose_milk_in_glass_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-rose-milk',
      product_id: 'prod-rose-milk',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-pom-juice',
    category_id: 'cat-beverages',
    name: 'Fresh Pomegranate Juice',
    description: 'Cold-pressed 100% fresh red ruby pomegranate juice with no added sugar.',
    price: 110,
    unit: '350ml',
    image_url: '/images/food/Pomegranate_juice_in_glass_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-pom-juice',
      product_id: 'prod-pom-juice',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-orange-juice',
    category_id: 'cat-beverages',
    name: 'Citrus Sweet Lime & Orange',
    description: 'Refreshing cold-pressed citrus juice bursting with vitamin C and natural electrolytes.',
    price: 95,
    unit: '350ml',
    image_url: '/images/food/Orange_juice_in_glass_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-orange-juice',
      product_id: 'prod-orange-juice',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },

  // ── Tikkas & Starters ──
  {
    id: 'prod-paneer-tikka',
    category_id: 'cat-tikkas',
    name: 'Tandoori Paneer Tikka',
    description: 'Fresh malai paneer cubes marinated in spiced yogurt and grilled to smoky perfection with bell peppers and onions.',
    price: 240,
    unit: '6 pcs',
    image_url: '/images/food/Paneer_tikka_on_white_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-paneer-tikka',
      product_id: 'prod-paneer-tikka',
      is_available: true,
      available_start_time: '11:00:00',
      available_end_time: '22:00:00',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-hariyali-tikka',
    category_id: 'cat-tikkas',
    name: 'Hariyali Paneer Tikka',
    description: 'Cottage cheese cubes tossed in fresh mint, coriander, and green chili pesto marinade, clay oven roasted.',
    price: 250,
    unit: '6 pcs',
    image_url: '/images/food/Hariyali_Paneer_Tikka_on_plate_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-hariyali-tikka',
      product_id: 'prod-hariyali-tikka',
      is_available: true,
      available_start_time: '11:00:00',
      available_end_time: '22:00:00',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-mushroom-tikka',
    category_id: 'cat-tikkas',
    name: 'Charcoal Mushroom Tikka',
    description: 'Juicy button mushrooms marinated in aromatic garam masala, ajwain, and hung curd, served with mint chutney.',
    price: 230,
    unit: '1 portion',
    image_url: '/images/food/Mushroom_tikka_on_white_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-mushroom-tikka',
      product_id: 'prod-mushroom-tikka',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-seekh-kebab',
    category_id: 'cat-tikkas',
    name: 'Royal Veg Seekh Kebab',
    description: 'Finely minced garden vegetables, paneer, and crushed nuts skewered and charred on glowing coals.',
    price: 220,
    unit: '4 skewers',
    image_url: '/images/food/Veg_Seekh_Kebab_on_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-seekh-kebab',
      product_id: 'prod-seekh-kebab',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },

  // ── Fried Rice & Bowls ──
  {
    id: 'prod-paneer-rice',
    category_id: 'cat-rice',
    name: 'Paneer Fried Rice',
    description: 'Fragrant basmati rice wok-tossed with golden paneer cubes, spring onions, crunchy carrots, and light soy sauce.',
    price: 190,
    unit: '1 bowl',
    image_url: '/images/food/Paneer_fried_rice_in_bowl_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-paneer-rice',
      product_id: 'prod-paneer-rice',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-schezwan-rice',
    category_id: 'cat-rice',
    name: 'Spicy Schezwan Veg Rice',
    description: 'Fiery wok-tossed long-grain rice with homemade Sichuan chili paste, crunchy celery, and bell peppers.',
    price: 180,
    unit: '1 bowl',
    image_url: '/images/food/Veg_Schezwan_Fried_Rice_bowl_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-schezwan-rice',
      product_id: 'prod-schezwan-rice',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-mushroom-rice',
    category_id: 'cat-rice',
    name: 'Garlic Mushroom Fried Rice',
    description: 'Fresh sliced button mushrooms and roasted garlic tossed with long grain rice and scallions.',
    price: 185,
    unit: '1 bowl',
    image_url: '/images/food/Mushroom_fried_rice_in_bowl_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-mushroom-rice',
      product_id: 'prod-mushroom-rice',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },

  // ── Naan & Parathas ──
  {
    id: 'prod-butter-naan',
    category_id: 'cat-breads',
    name: 'Tandoori Butter Naan',
    description: 'Classic leavened flatbread baked on the walls of the tandoor, brushed generously with pure butter.',
    price: 55,
    unit: '1 pc',
    image_url: '/images/food/Butter_Naan_on_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-butter-naan',
      product_id: 'prod-butter-naan',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-garlic-naan',
    category_id: 'cat-breads',
    name: 'Garlic Butter Naan',
    description: 'Crispy oven-baked naan stuffed with roasted garlic cloves and fresh cilantro, topped with melted butter.',
    price: 65,
    unit: '1 pc',
    image_url: '/images/food/Garlic_Naan_plated_on_dish_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-garlic-naan',
      product_id: 'prod-garlic-naan',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-paneer-paratha',
    category_id: 'cat-breads',
    name: 'Amritsari Paneer Paratha',
    description: 'Whole wheat flatbread stuffed with spiced grated paneer, green chilies, and fresh coriander, served with curd and pickle.',
    price: 95,
    unit: '1 pc',
    image_url: '/images/food/Paneer_paratha_on_a_plate_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-paneer-paratha',
      product_id: 'prod-paneer-paratha',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-aloo-paratha',
    category_id: 'cat-breads',
    name: 'Classic Aloo Paratha',
    description: 'Golden griddle-cooked paratha filled with spiced mashed potatoes, toasted cumin, and mint.',
    price: 80,
    unit: '1 pc',
    image_url: '/images/food/Aloo_Paratha_on_plate_202608251905.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-aloo-paratha',
      product_id: 'prod-aloo-paratha',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },

  // ── Combos & Gift Boxes ──
  {
    id: 'prod-festive-box',
    category_id: 'cat-combos',
    name: 'Grand Festive Celebration Box',
    description: 'Handpicked assortment of signature ghee sweets, premium dry fruit delicacies, and savory snacks in an elegant gold tin.',
    price: 850,
    unit: '1 kg Box',
    image_url: '/images/ecommerce/Festive Combo.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-festive-box',
      product_id: 'prod-festive-box',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
  {
    id: 'prod-snack-platter',
    category_id: 'cat-combos',
    name: 'Evening Chai Snack Platter',
    description: 'Assorted hot and crispy savouries crafted fresh every morning with traditional secret family spices.',
    price: 420,
    unit: '500g',
    image_url: '/images/ecommerce/snacks.jpeg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    availability: {
      id: 'av-snack-platter',
      product_id: 'prod-snack-platter',
      is_available: true,
      available_start_time: null,
      available_end_time: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

export const SEED_DELIVERY_ZONES: JayaramMittaiDeliveryZone[] = [
  {
    id: 'zone-nanganallur',
    name: 'Nanganallur',
    center_lat: 12.9806,
    center_lng: 80.1912,
    radius_km: 4.0,
    is_enabled: true,
    delivery_charge_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'zone-chromepet',
    name: 'Chromepet',
    center_lat: 12.9516,
    center_lng: 80.1462,
    radius_km: 10.0,
    is_enabled: true,
    delivery_charge_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'zone-tambaram',
    name: 'Tambaram',
    center_lat: 12.9249,
    center_lng: 80.1000,
    radius_km: 12.0,
    is_enabled: true,
    delivery_charge_override: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_DELIVERY_RULES: JayaramMittaiDeliveryRule[] = [
  {
    id: 'rule-under-5km',
    max_distance_km: 5.0,
    delivery_charge: 50.0,
    estimated_hours: 2.0,
    free_delivery_threshold: 1000.0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-under-8km',
    max_distance_km: 8.0,
    delivery_charge: 100.0,
    estimated_hours: 3.0,
    free_delivery_threshold: 1000.0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rule-under-11km',
    max_distance_km: 11.0,
    delivery_charge: 100.0,
    estimated_hours: 4.0,
    free_delivery_threshold: 1000.0,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_OPERATIONAL_HOURS: JayaramMittaiOperationalHours[] = [
  {
    id: 'op-default',
    day_of_week: null,
    open_time: '09:00:00',
    close_time: '17:00:00',
    is_closed: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
